# Generated by Django 4.2.2 on 2023-07-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pdf_file', models.FileField(upload_to='group_pdfs')),
                ('developers', models.ManyToManyField(related_name='groups', to='project_task.employee')),
            ],
        ),
    ]
