# Generated by Django 4.2.2 on 2023-07-14 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_task', '0002_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='pdf_file',
        ),
    ]
