# Generated by Django 4.2.3 on 2023-07-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_task', '0004_task_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Start', 'Start'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=15),
        ),
    ]
