# Generated by Django 4.2.3 on 2023-07-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_task', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Start', 'Start'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=15),
        ),
    ]
