# Generated by Django 4.2.3 on 2023-07-16 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_task', '0007_projectmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectManager',
        ),
    ]
