# Generated by Django 4.2.3 on 2023-07-17 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_task', '0008_delete_projectmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='project_manager',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_task.employee'),
        ),
    ]
