# Generated by Django 4.2.3 on 2023-07-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_task', '0013_group_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
