# Generated by Django 4.2.3 on 2023-07-26 13:20

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('project_task', '0015_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
