# Generated by Django 4.2.3 on 2023-07-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_task', '0017_employee_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='technologies_used',
            field=models.TextField(blank=True, null=True),
        ),
    ]
