# Generated by Django 4.2.3 on 2023-08-05 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_task', '0022_tasknote'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknote',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
